apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: py-test-nov13-gitops
  description: This is GitOps manifest for py-test-nov13   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: py-test-nov13
    backstage.io/kubernetes-id: py-test-nov13 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: py-test-nov13   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:py-test-nov13
